project:
  type: website
  output-dir: docs

website:
  title: "campr"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: team.qmd
        text: Team
      - href: introduction.qmd
        text: Introduction
      - href: data.qmd
        text: Data
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



